### ISSUE TITLE
`bg-opacity` and `text-opacity` solution

### ISSUE THREAD

**Issue by isBatak** [astahmer/tw2panda#7]
Currently `bg-opacity` is ignored
```jsx
<div className="bg-indigo-600 bg-opacity-50" />
```
```jsx
<div className={css({ bgColor: 'indigo.600' })} />
```

Is there a way to somehow support this transformation.
Panda CSS currently does not have a solution for transparent colors, but maybe some custom `tailwind` preset could solve this.
Tailwind is using css variables with each color like this
```css
.bg-opacity-50 {
    --tw-bg-opacity: 0.5;
}
.bg-indigo-600 {
    --tw-bg-opacity: 1;
    background-color: rgba(79,70,229,var(--tw-bg-opacity));
}
.text-opacity-25 {
    --tw-text-opacity: 0.25;
}
.text-white {
    --tw-text-opacity: 1;
    color: rgba(255,255,255,var(--tw-text-opacity));
}
```
But until Panda add something similar maybe tw2panda could just transform it to css variable like this
```jsx
<div 
  style={{ `--tw-bg-opacity`: 0.5 }}
  className={css({ 
    bgColor: 'indigo.600'
  })} 
/>
```
and provide tailwind colors preset
